version: '3.8'

services:
  db:
    image: postgres:17-alpine
    container_name: library_db_compose
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - library_db_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

  api:
    build: .
    container_name: library_api_compose
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=postgres
      - DB_SSLMODE=disable
    depends_on:
      - db

volumes:
  library_db_data:
